- title: JavaScript Fundamentals
  id: jsfun
  length: 2hrs
  start: 9:30am, Wednesday
  level: Beginner
  desc: >
    JavaScript is one of the world’s most popular programming languages, used
    by virtually all web applications. Learn the basics with this focused
    introduction to JavaScript Fundamentals. From variable types and functions
    to scope and prototype chains, you’ll gain a solid understanding of the
    language and a firm foundation for creating real world applications while
    writing clean, maintainable JavaScript.

- title: Intro to Node.js
  id: nodejs
  length: 3hrs
  start: 12:45pm, Wednesday
  level: Beginner
  desc: >
    In this intensive training segment, we’re going to get you started
    developing in Node.js. We’ll build a small application that serves a static
    webpage, has dynamic routing, and interacts with a third-party API (maybe
    even of the NodeBot variety...?). No knowledge of Node.js necessary, though
    a knowledge of JavaScript is a good thing to have for this training.

- title: Debugging Deep Dive
  id: debug
  length: 2hrs
  start: 9:30am, Friday
  level: Beginner
  desc: >
    Debugging is one of those things that (almost) everyone despises, but that
    absolutely every software developer needs to know how to do. Over the past
    fifteen years, Brian has worked through some of the weirdest, wildest bits
    of JavaScript, and has the mental scars to prove it.

    In this deep dive, come and absorb some of his knowledge on how to debug
    all the things! We'll be focusing on the front-end mostly, as that's more
    commonly where the weirdness happens. We'll explore devtools in various
    browsers, as well as use of tools like proxies to help figure out what the
    heck is wrong with things.

- title: ES6 Overview Workshop
  id: es6
  start: 12:45pm, Friday
  length: 1.5hrs
  level: Intermediate
  desc: >
    Coming soon, in a theater near you. It’s bigger than Ultron. It’s better
    than Ultron. It’s more ubiquitous than Robert Downey Jr. It’s ES6,
    JavaScript’s next in-your-face revsion. You’ve never seen a sequel, until
    you’ve seen this.

    I’d like to take you all to the movies. Explain to you all about ES6, and
    what new features are accessible now, even in older browsers or node.js.
    You’ll see what we can access with a single new script tag. I’ll also go
    through many of the features that are “transpilable” and explain what that
    means. I’ll even go so far as to say why some don’t like the word
    “transpile” at all. It’ll be an excuse for me to get into the fun and
    tangled web of compilers.

    The goal of this workshop will be to give everyone a taste and experience
    of the future JavaScript features that we can all use with only a few
    tweaks to our current processes.

- title: Introduction and Getting Started with React.js
  id: react
  start: 2:15pm, Friday
  length: 1.5hrs
  level: Intermediate
  desc: >
    Why is React.js a game changer in a world with so many UI frameworks? We'll
    have fun learning what makes React.js special and uncover its simple core
    concepts. As we continue our journey, we'll apply our React.js skills to
    building some reactive web apps. You'll emerge from this workshop knowing
    the basics of React.js and will be ready to use it for your own projects.
